name: Arconix
description: Arconix
version: 1.0.6
main: com.songoda.arconix.Arconix
authors: [Songoda, TheCrystalStar]
commands:
  Arconix:
    description: Main command for ArconixAPI
    aliases: [ar]